### ISSUE TITLE
Lengthy tasks get cut off

### ISSUE THREAD

**Issue by ryanaltvater** [rampatra/todobar-community#5]
![Screenshot 2024-11-01 at 5 10 58 PM](https://github.com/user-attachments/assets/421e4e47-df3e-4c51-aaed-9eaf9d98b274)

**Steps to reproduce:**
1. Open the app
2. Enter a task that's about 42 characters long
3. Hit "Enter" to start a new task, or...
4. Click out of the task list
5. Click back into the task list
6. Task text is cut off

**Comments:**
There's no easy way to read text that extends beyond the task window without clicking into the task and clicking/dragging the cursor to the right, or using the arrow keys to move the cursor towards the end of the task. The desired experience would be to wrap the text to a new line.

**Comment by rampatra** [comment]
![CleanShot 2024-11-07 at 15 57 59@2x](https://github.com/user-attachments/assets/b0dd0b76-931b-474d-a05a-ed37c300e43e)

You can increase your ToDoBar window width as shown above if you prefer to write longer texts. Having said that, I believe that most of the tasks can be shortened. Moreover, there's a feature of Todobar that shows your next pending task on the menu bar itself so if you have too long tasks then it will take up all the space on your menu bar.

**Comment by ryanaltvater** [comment]
That's fair. Honestly, I discovered that setting after I created this as an issue. I didn't close it because I've been 50/50 on the adjustable window size setting. I think I could get used to it though.

Thanks for the response!
