### ISSUE TITLE
Empty task remains persistent and won't go away

### ISSUE THREAD

**Issue by ryanaltvater** [rampatra/todobar-community#7]
![Screenshot 2024-11-04 at 4 57 47 PM](https://github.com/user-attachments/assets/a0f78279-2434-4835-ad8e-2cd07eef0cf0)

**Steps to reproduce:**
1. Open the app
2. Hit "Enter" to start a new task
3. Click out of the task list
4. Click back into the task list
5. New (empty) task is still visible

**Comments:**
Once I click out of the task list to close it, the app should remove an empty task by default.

**Comment by rampatra** [comment]
The fix for https://github.com/rampatra/todobar-community/issues/3 will have the cursor on the last empty field such that the user can quickly add a new to-do. So, this field will stay but the cursor will be there every time you open ToDoBar.

**Comment by rampatra** [comment]
I wouldn't hide this field as this behavior was there before and people were confused and didn't know how to add a new to-do. Therefore, I decided to add an empty field where the user can quickly add a new to-do.

**Comment by ryanaltvater** [comment]
If you’re saying you’re going to permanently show the field for adding new tasks and not add any other interactions to the UI to add new tasks, then I think that’s all you can do.

My issue was that the field isn’t there when I first launch the app, it’s not there when I hit “Esc” on it, and when I click out of the app and open it back up, it’s still there. I don’t think that’s a direct reflection of knowing how to add a task or not. If I hit “Enter” then I know it added a new empty task field, but when I click out of the app and back into it, that field remains UNTIL I click into the empty field and hit “Esc”. Those steps seem unnecessary if I change my mind about adding a new task. If I accidentally hit “Enter” or I go to add a new task and don’t want to after all, I should just be able to click out of the app and it resets that empty field rather than me having to click into it to hit “Esc” and remove it. Seems like more of a small quality of life improvement.

**Comment by ryanaltvater** [comment]
This has been resolved, and can be closed.
